# Generated by Django 5.0.6 on 2026-03-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField()),
                ('browser', models.CharField(max_length=50, null=True)),
                ('os', models.CharField(max_length=50, null=True)),
                ('device_type', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('screen_width', models.IntegerField(null=True)),
                ('screen_height', models.IntegerField(null=True)),
                ('language', models.CharField(max_length=20, null=True)),
                ('timezone', models.CharField(max_length=50, null=True)),
                ('page_url', models.TextField()),
                ('page_title', models.TextField()),
                ('referrer', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
